class Move:
    def __init__(self, name, type, category, pp, **kwargs):
        self.name = name
        self.type = type
        self.category = category
        self.pp = pp
        self.args = {}
        for key, val in kwargs.items():
            self.args[key] = val
            setattr(self, key, val)

moveList = {
    'pound': Move('pound', 'normal', 'physical', 35, power=40, accuracy=100),
    'karate-chop': Move('karate-chop', 'fighting', 'physical', 25, power=50, accuracy=100, critRate=1),
    'double-slap': Move('double-slap', 'normal', 'physical', 10, power=15, accuracy=85, minHits=2, maxHits=5),
    'comet-punch': Move('comet-punch', 'normal', 'physical', 15, power=18, accuracy=85, minHits=2, maxHits=5),
    'mega-punch': Move('mega-punch', 'normal', 'physical', 20, power=80, accuracy=85),
    'pay-day': Move('pay-day', 'normal', 'physical', 20, power=40, accuracy=100),
    'fire-punch': Move('fire-punch', 'fire', 'physical', 15, power=75, accuracy=100, ailment='burn', ailmentChance=0),
    'ice-punch': Move('ice-punch', 'ice', 'physical', 15, power=75, accuracy=100, ailment='freeze', ailmentChance=0),
    'thunder-punch': Move('thunder-punch', 'electric', 'physical', 15, power=75, accuracy=100, ailment='paralysis', ailmentChance=0),
    'scratch': Move('scratch', 'normal', 'physical', 35, power=40, accuracy=100),
    'vice-grip': Move('vice-grip', 'normal', 'physical', 30, power=55, accuracy=100),
    'guillotine': Move('guillotine', 'normal', 'physical', 5, accuracy=30),
    'razor-wind': Move('razor-wind', 'normal', 'special', 10, power=80, accuracy=100, critRate=1),
    'swords-dance': Move('swords-dance', 'normal', 'status', 20, stats=['atk'], statsStage=[2]),
    'cut': Move('cut', 'normal', 'physical', 30, power=50, accuracy=95),
    'gust': Move('gust', 'flying', 'special', 35, power=40, accuracy=100),
    'wing-attack': Move('wing-attack', 'flying', 'physical', 35, power=60, accuracy=100),
    'whirlwind': Move('whirlwind', 'normal', 'status', 20, priority=-6),
    'fly': Move('fly', 'flying', 'physical', 15, power=90, accuracy=95),
    'bind': Move('bind', 'normal', 'physical', 20, power=15, accuracy=85, ailment='trap', ailmentChance=0, minTurns=5, maxTurns=6),
    'slam': Move('slam', 'normal', 'physical', 20, power=80, accuracy=75),
    'vine-whip': Move('vine-whip', 'grass', 'physical', 25, power=45, accuracy=100),
    'stomp': Move('stomp', 'normal', 'physical', 20, power=65, accuracy=100, flinchChance=30),
    'double-kick': Move('double-kick', 'fighting', 'physical', 30, power=30, accuracy=100, minHits=2, maxHits=2),
    'mega-kick': Move('mega-kick', 'normal', 'physical', 5, power=120, accuracy=75),
    'jump-kick': Move('jump-kick', 'fighting', 'physical', 10, power=100, accuracy=95),
    'rolling-kick': Move('rolling-kick', 'fighting', 'physical', 15, power=60, accuracy=85, flinchChance=30),
    'sand-attack': Move('sand-attack', 'ground', 'status', 15, accuracy=100, stats=['acc'], statsStage=[-1]),
    'headbutt': Move('headbutt', 'normal', 'physical', 15, power=70, accuracy=100, flinchChance=30),
    'horn-attack': Move('horn-attack', 'normal', 'physical', 25, power=65, accuracy=100),
    'fury-attack': Move('fury-attack', 'normal', 'physical', 20, power=15, accuracy=85, minHits=2, maxHits=5),
    'horn-drill': Move('horn-drill', 'normal', 'physical', 5, accuracy=30),
    'tackle': Move('tackle', 'normal', 'physical', 35, power=40, accuracy=100),
    'body-slam': Move('body-slam', 'normal', 'physical', 15, power=85, accuracy=100, ailment='paralysis', ailmentChance=0),
    'wrap': Move('wrap', 'normal', 'physical', 20, power=15, accuracy=90, ailment='trap', ailmentChance=0, minTurns=5, maxTurns=6),
    'take-down': Move('take-down', 'normal', 'physical', 20, power=90, accuracy=85, dragin=-25),
    'thrash': Move('thrash', 'normal', 'physical', 10, power=120, accuracy=100),
    'double-edge': Move('double-edge', 'normal', 'physical', 15, power=120, accuracy=100, dragin=-33),
    'tail-whip': Move('tail-whip', 'normal', 'status', 30, accuracy=100, stats=['def'], statsStage=[-1]),
    'poison-sting': Move('poison-sting', 'poison', 'physical', 35, power=15, accuracy=100, ailment='poison', ailmentChance=0),
    'twineedle': Move('twineedle', 'bug', 'physical', 20, power=25, accuracy=100, ailment='poison', ailmentChance=0, minHits=2, maxHits=2),
    'pin-missile': Move('pin-missile', 'bug', 'physical', 20, power=25, accuracy=95, minHits=2, maxHits=5),
    'leer': Move('leer', 'normal', 'status', 30, accuracy=100, stats=['def'], statsStage=[-1], statsChance=100),
    'bite': Move('bite', 'dark', 'physical', 25, power=60, accuracy=100, flinchChance=30),
    'growl': Move('growl', 'normal', 'status', 40, accuracy=100, stats=['atk'], statsStage=[-1]),
    'roar': Move('roar', 'normal', 'status', 20, priority=-6),
    'sing': Move('sing', 'normal', 'status', 15, accuracy=55, ailment='sleep', minTurns=2, maxTurns=4),
    'supersonic': Move('supersonic', 'normal', 'status', 20, accuracy=55, ailment='confusion', minTurns=2, maxTurns=5),
    'sonic-boom': Move('sonic-boom', 'normal', 'special', 20, accuracy=90),
    'disable': Move('disable', 'normal', 'status', 20, accuracy=100, ailment='disable', minTurns=4, maxTurns=4),
    'acid': Move('acid', 'poison', 'special', 30, power=40, accuracy=100, stats=['spDef'], statsStage=[-1], statsChance=10),
    'ember': Move('ember', 'fire', 'special', 25, power=40, accuracy=100, ailment='burn', ailmentChance=0),
    'flamethrower': Move('flamethrower', 'fire', 'special', 15, power=90, accuracy=100, ailment='burn', ailmentChance=0),
    'mist': Move('mist', 'ice', 'status', 30),
    'water-gun': Move('water-gun', 'water', 'special', 25, power=40, accuracy=100),
    'hydro-pump': Move('hydro-pump', 'water', 'special', 5, power=110, accuracy=80),
    'surf': Move('surf', 'water', 'special', 15, power=90, accuracy=100),
    'ice-beam': Move('ice-beam', 'ice', 'special', 10, power=90, accuracy=100, ailment='freeze', ailmentChance=0),
    'blizzard': Move('blizzard', 'ice', 'special', 5, power=110, accuracy=70, ailment='freeze', ailmentChance=0),
    'psybeam': Move('psybeam', 'psychic', 'special', 20, power=65, accuracy=100, ailment='confusion', ailmentChance=0, minTurns=2, maxTurns=5),
    'bubble-beam': Move('bubble-beam', 'water', 'special', 20, power=65, accuracy=100, stats=['speed'], statsStage=[-1], statsChance=10),
    'aurora-beam': Move('aurora-beam', 'ice', 'special', 20, power=65, accuracy=100, stats=['atk'], statsStage=[-1], statsChance=10),
    'hyper-beam': Move('hyper-beam', 'normal', 'special', 5, power=150, accuracy=90),
    'peck': Move('peck', 'flying', 'physical', 35, power=35, accuracy=100),
    'drill-peck': Move('drill-peck', 'flying', 'physical', 20, power=80, accuracy=100),
    'submission': Move('submission', 'fighting', 'physical', 20, power=80, accuracy=80, dragin=-25),
    'low-kick': Move('low-kick', 'fighting', 'physical', 20, accuracy=100),
    'counter': Move('counter', 'fighting', 'physical', 20, accuracy=100, priority=-5),
    'seismic-toss': Move('seismic-toss', 'fighting', 'physical', 20, accuracy=100),
    'strength': Move('strength', 'normal', 'physical', 15, power=80, accuracy=100),
    'absorb': Move('absorb', 'grass', 'special', 25, power=20, accuracy=100, dragin=50),
    'mega-drain': Move('mega-drain', 'grass', 'special', 15, power=40, accuracy=100, dragin=50),
    'leech-seed': Move('leech-seed', 'grass', 'status', 10, accuracy=90, ailment='leech-seed'),
    'growth': Move('growth', 'normal', 'status', 20, stats=['atk', 'spAtk'], statsStage=[1, 1]),
    'razor-leaf': Move('razor-leaf', 'grass', 'physical', 25, power=55, accuracy=95, critRate=1),
    'solar-beam': Move('solar-beam', 'grass', 'special', 10, power=120, accuracy=100),
    'poison-powder': Move('poison-powder', 'poison', 'status', 35, accuracy=75, ailment='poison'),
    'stun-spore': Move('stun-spore', 'grass', 'status', 30, accuracy=75, ailment='paralysis'),
    'sleep-powder': Move('sleep-powder', 'grass', 'status', 15, accuracy=75, ailment='sleep', minTurns=2, maxTurns=4),
    'petal-dance': Move('petal-dance', 'grass', 'special', 10, power=120, accuracy=100),
    'string-shot': Move('string-shot', 'bug', 'status', 40, accuracy=95, stats=['speed'], statsStage=[-2]),
    'dragon-rage': Move('dragon-rage', 'dragon', 'special', 10, accuracy=100),
    'fire-spin': Move('fire-spin', 'fire', 'special', 15, power=35, accuracy=85, ailment='trap', ailmentChance=0, minTurns=5, maxTurns=6),
    'thunder-shock': Move('thunder-shock', 'electric', 'special', 30, power=40, accuracy=100, ailment='paralysis', ailmentChance=0),
    'thunderbolt': Move('thunderbolt', 'electric', 'special', 15, power=90, accuracy=100, ailment='paralysis', ailmentChance=0),
    'thunder-wave': Move('thunder-wave', 'electric', 'status', 20, accuracy=90, ailment='paralysis'),
    'thunder': Move('thunder', 'electric', 'special', 10, power=110, accuracy=70, ailment='paralysis', ailmentChance=0),
    'rock-throw': Move('rock-throw', 'rock', 'physical', 15, power=50, accuracy=90),
    'earthquake': Move('earthquake', 'ground', 'physical', 10, power=100, accuracy=100),
    'fissure': Move('fissure', 'ground', 'physical', 5, accuracy=30),
    'dig': Move('dig', 'ground', 'physical', 10, power=80, accuracy=100),
    'toxic': Move('toxic', 'poison', 'status', 10, accuracy=90, ailment='poison', minTurns=15, maxTurns=15),
    'confusion': Move('confusion', 'psychic', 'special', 25, power=50, accuracy=100, ailment='confusion', ailmentChance=0, minTurns=2, maxTurns=5),
    'psychic': Move('psychic', 'psychic', 'special', 10, power=90, accuracy=100, stats=['spDef'], statsStage=[-1], statsChance=10),
    'hypnosis': Move('hypnosis', 'psychic', 'status', 20, accuracy=60, ailment='sleep', minTurns=2, maxTurns=4),
    'meditate': Move('meditate', 'psychic', 'status', 40, stats=['atk'], statsStage=[1]),
    'agility': Move('agility', 'psychic', 'status', 30, stats=['speed'], statsStage=[2]),
    'quick-attack': Move('quick-attack', 'normal', 'physical', 30, power=40, accuracy=100, priority=1),
    'rage': Move('rage', 'normal', 'physical', 20, power=20, accuracy=100),
    'teleport': Move('teleport', 'psychic', 'status', 20, priority=-6),
    'night-shade': Move('night-shade', 'ghost', 'special', 15, accuracy=100),
    'mimic': Move('mimic', 'normal', 'status', 10),
    'screech': Move('screech', 'normal', 'status', 40, accuracy=85, stats=['def'], statsStage=[-2]),
    'double-team': Move('double-team', 'normal', 'status', 15, stats=['eva'], statsStage=[1]),
    'recover': Move('recover', 'normal', 'status', 10, healing=50),
    'harden': Move('harden', 'normal', 'status', 30, stats=['def'], statsStage=[1]),
    'minimize': Move('minimize', 'normal', 'status', 10, stats=['eva'], statsStage=[2]),
    'smokescreen': Move('smokescreen', 'normal', 'status', 20, accuracy=100, stats=['acc'], statsStage=[-1]),
    'confuse-ray': Move('confuse-ray', 'ghost', 'status', 10, accuracy=100, ailment='confusion', minTurns=2, maxTurns=5),
    'withdraw': Move('withdraw', 'water', 'status', 40, stats=['def'], statsStage=[1]),
    'defense-curl': Move('defense-curl', 'normal', 'status', 40, stats=['def'], statsStage=[1]),
    'barrier': Move('barrier', 'psychic', 'status', 20, stats=['def'], statsStage=[2]),
    'light-screen': Move('light-screen', 'psychic', 'status', 30),
    'haze': Move('haze', 'ice', 'status', 30),
    'reflect': Move('reflect', 'psychic', 'status', 20),
    'focus-energy': Move('focus-energy', 'normal', 'status', 30),
    'bide': Move('bide', 'normal', 'physical', 10, priority=1),
    'metronome': Move('metronome', 'normal', 'status', 10),
    'mirror-move': Move('mirror-move', 'flying', 'status', 20),
    'self-destruct': Move('self-destruct', 'normal', 'physical', 5, power=200, accuracy=100),
    'egg-bomb': Move('egg-bomb', 'normal', 'physical', 10, power=100, accuracy=75),
    'lick': Move('lick', 'ghost', 'physical', 30, power=30, accuracy=100, ailment='paralysis', ailmentChance=0),
    'smog': Move('smog', 'poison', 'special', 20, power=30, accuracy=70, ailment='poison', ailmentChance=0),
    'sludge': Move('sludge', 'poison', 'special', 20, power=65, accuracy=100, ailment='poison', ailmentChance=0),
    'bone-club': Move('bone-club', 'ground', 'physical', 20, power=65, accuracy=85, flinchChance=10),
    'fire-blast': Move('fire-blast', 'fire', 'special', 5, power=110, accuracy=85, ailment='burn', ailmentChance=0),
    'waterfall': Move('waterfall', 'water', 'physical', 15, power=80, accuracy=100, flinchChance=20),
    'clamp': Move('clamp', 'water', 'physical', 15, power=35, accuracy=85, ailment='trap', ailmentChance=0, minTurns=5, maxTurns=6),
    'swift': Move('swift', 'normal', 'special', 20, power=60),
    'skull-bash': Move('skull-bash', 'normal', 'physical', 10, power=130, accuracy=100, ailmentChance=0),
    'spike-cannon': Move('spike-cannon', 'normal', 'physical', 15, power=20, accuracy=100, minHits=2, maxHits=5),
    'constrict': Move('constrict', 'normal', 'physical', 35, power=10, accuracy=100, stats=['speed'], statsStage=[-1], statsChance=10),
    'amnesia': Move('amnesia', 'psychic', 'status', 20, stats=['spDef'], statsStage=[2]),
    'kinesis': Move('kinesis', 'psychic', 'status', 15, accuracy=80, stats=['acc'], statsStage=[-1]),
    'soft-boiled': Move('soft-boiled', 'normal', 'status', 10, healing=50),
    'high-jump-kick': Move('high-jump-kick', 'fighting', 'physical', 10, power=130, accuracy=90),
    'glare': Move('glare', 'normal', 'status', 30, accuracy=100, ailment='paralysis'),
    'dream-eater': Move('dream-eater', 'psychic', 'special', 15, power=100, accuracy=100, dragin=50),
    'poison-gas': Move('poison-gas', 'poison', 'status', 40, accuracy=90, ailment='poison'),
    'barrage': Move('barrage', 'normal', 'physical', 20, power=15, accuracy=85, minHits=2, maxHits=5),
    'leech-life': Move('leech-life', 'bug', 'physical', 10, power=80, accuracy=100, dragin=50),
    'lovely-kiss': Move('lovely-kiss', 'normal', 'status', 10, accuracy=75, ailment='sleep', minTurns=2, maxTurns=4),
    'sky-attack': Move('sky-attack', 'flying', 'physical', 5, power=140, accuracy=90, critRate=1, flinchChance=30),
    'transform': Move('transform', 'normal', 'status', 10),
    'bubble': Move('bubble', 'water', 'special', 30, power=40, accuracy=100, stats=['speed'], statsStage=[-1], statsChance=10),
    'dizzy-punch': Move('dizzy-punch', 'normal', 'physical', 10, power=70, accuracy=100, ailment='confusion', ailmentChance=0, minTurns=2, maxTurns=5),
    'spore': Move('spore', 'grass', 'status', 15, accuracy=100, ailment='sleep', minTurns=2, maxTurns=4),
    'flash': Move('flash', 'normal', 'status', 20, accuracy=100, stats=['acc'], statsStage=[-1]),
    'psywave': Move('psywave', 'psychic', 'special', 15, accuracy=100),
    'splash': Move('splash', 'normal', 'status', 40),
    'acid-armor': Move('acid-armor', 'poison', 'status', 20, stats=['def'], statsStage=[2]),
    'crabhammer': Move('crabhammer', 'water', 'physical', 10, power=100, accuracy=90, critRate=1),
    'explosion': Move('explosion', 'normal', 'physical', 5, power=250, accuracy=100),
    'fury-swipes': Move('fury-swipes', 'normal', 'physical', 15, power=18, accuracy=80, minHits=2, maxHits=5),
    'bonemerang': Move('bonemerang', 'ground', 'physical', 10, power=50, accuracy=90, minHits=2, maxHits=2),
    'rest': Move('rest', 'psychic', 'status', 10),
    'rock-slide': Move('rock-slide', 'rock', 'physical', 10, power=75, accuracy=90, flinchChance=30),
    'hyper-fang': Move('hyper-fang', 'normal', 'physical', 15, power=80, accuracy=90, flinchChance=10),
    'sharpen': Move('sharpen', 'normal', 'status', 30, stats=['atk'], statsStage=[1]),
    'conversion': Move('conversion', 'normal', 'status', 30),
    'tri-attack': Move('tri-attack', 'normal', 'special', 10, power=80, accuracy=100, ailment='unknown', ailmentChance=0),
    'super-fang': Move('super-fang', 'normal', 'physical', 10, accuracy=90),
    'slash': Move('slash', 'normal', 'physical', 20, power=70, accuracy=100, critRate=1),
    'substitute': Move('substitute', 'normal', 'status', 10),
    'struggle': Move('struggle', 'normal', 'physical', 1, power=50, healing=-25),
    'sketch': Move('sketch', 'normal', 'status', 1),
    'triple-kick': Move('triple-kick', 'fighting', 'physical', 10, power=10, accuracy=90, minHits=3, maxHits=3),
    'thief': Move('thief', 'dark', 'physical', 25, power=60, accuracy=100),
    'spider-web': Move('spider-web', 'bug', 'status', 10),
    'mind-reader': Move('mind-reader', 'normal', 'status', 5),
    'nightmare': Move('nightmare', 'ghost', 'status', 15, accuracy=100, ailment='nightmare'),
    'flame-wheel': Move('flame-wheel', 'fire', 'physical', 25, power=60, accuracy=100, ailment='burn', ailmentChance=0),
    'snore': Move('snore', 'normal', 'special', 15, power=50, accuracy=100, flinchChance=30),
    'curse': Move('curse', 'ghost', 'status', 10),
    'flail': Move('flail', 'normal', 'physical', 15, accuracy=100),
    'conversion-2': Move('conversion-2', 'normal', 'status', 30),
    'aeroblast': Move('aeroblast', 'flying', 'special', 5, power=100, accuracy=95, critRate=1),
    'cotton-spore': Move('cotton-spore', 'grass', 'status', 40, accuracy=100, stats=['speed'], statsStage=[-2]),
    'reversal': Move('reversal', 'fighting', 'physical', 15, accuracy=100),
    'spite': Move('spite', 'ghost', 'status', 10, accuracy=100),
    'powder-snow': Move('powder-snow', 'ice', 'special', 25, power=40, accuracy=100, ailment='freeze', ailmentChance=0),
    'protect': Move('protect', 'normal', 'status', 10, priority=4),
    'mach-punch': Move('mach-punch', 'fighting', 'physical', 30, power=40, accuracy=100, priority=1),
    'scary-face': Move('scary-face', 'normal', 'status', 10, accuracy=100, stats=['speed'], statsStage=[-2]),
    'feint-attack': Move('feint-attack', 'dark', 'physical', 20, power=60),
    'sweet-kiss': Move('sweet-kiss', 'fairy', 'status', 10, accuracy=75, ailment='confusion', minTurns=2, maxTurns=5),
    'belly-drum': Move('belly-drum', 'normal', 'status', 10),
    'sludge-bomb': Move('sludge-bomb', 'poison', 'special', 10, power=90, accuracy=100, ailment='poison', ailmentChance=0),
    'mud-slap': Move('mud-slap', 'ground', 'special', 10, power=20, accuracy=100, stats=['acc'], statsStage=[-1], statsChance=100),
    'octazooka': Move('octazooka', 'water', 'special', 10, power=65, accuracy=85, stats=['acc'], statsStage=[-1], statsChance=50),
    'spikes': Move('spikes', 'ground', 'status', 20),
    'zap-cannon': Move('zap-cannon', 'electric', 'special', 5, power=120, accuracy=50, ailment='paralysis', ailmentChance=0),
    'foresight': Move('foresight', 'normal', 'status', 40, ailment='no-type-immunity'),
    'destiny-bond': Move('destiny-bond', 'ghost', 'status', 5),
    'perish-song': Move('perish-song', 'normal', 'status', 5, ailment='perish-song', minTurns=4, maxTurns=4),
    'icy-wind': Move('icy-wind', 'ice', 'special', 15, power=55, accuracy=95, stats=['speed'], statsStage=[-1], statsChance=100),
    'detect': Move('detect', 'fighting', 'status', 5, priority=4),
    'bone-rush': Move('bone-rush', 'ground', 'physical', 10, power=25, accuracy=90, minHits=2, maxHits=5),
    'lock-on': Move('lock-on', 'normal', 'status', 5),
    'outrage': Move('outrage', 'dragon', 'physical', 10, power=120, accuracy=100),
    'sandstorm': Move('sandstorm', 'rock', 'status', 10),
    'giga-drain': Move('giga-drain', 'grass', 'special', 10, power=75, accuracy=100, dragin=50),
    'endure': Move('endure', 'normal', 'status', 10, priority=4),
    'charm': Move('charm', 'fairy', 'status', 20, accuracy=100, stats=['atk'], statsStage=[-2]),
    'rollout': Move('rollout', 'rock', 'physical', 20, power=30, accuracy=90),
    'false-swipe': Move('false-swipe', 'normal', 'physical', 40, power=40, accuracy=100),
    'swagger': Move('swagger', 'normal', 'status', 15, accuracy=85, stats=['atk'], statsStage=[2], ailment='confusion', minTurns=2, maxTurns=5),
    'milk-drink': Move('milk-drink', 'normal', 'status', 10, healing=50),
    'spark': Move('spark', 'electric', 'physical', 20, power=65, accuracy=100, ailment='paralysis', ailmentChance=0),
    'fury-cutter': Move('fury-cutter', 'bug', 'physical', 20, power=40, accuracy=95),
    'steel-wing': Move('steel-wing', 'steel', 'physical', 25, power=70, accuracy=90, stats=['def'], statsStage=[1], statsChance=10),
    'mean-look': Move('mean-look', 'normal', 'status', 5),
    'attract': Move('attract', 'normal', 'status', 15, accuracy=100, ailment='infatuation'),
    'sleep-talk': Move('sleep-talk', 'normal', 'status', 10),
    'heal-bell': Move('heal-bell', 'normal', 'status', 5),
    'return': Move('return', 'normal', 'physical', 20, accuracy=100),
    'present': Move('present', 'normal', 'physical', 15, accuracy=90),
    'frustration': Move('frustration', 'normal', 'physical', 20, accuracy=100),
    'safeguard': Move('safeguard', 'normal', 'status', 25),
    'pain-split': Move('pain-split', 'normal', 'status', 20),
    'sacred-fire': Move('sacred-fire', 'fire', 'physical', 5, power=100, accuracy=95, ailment='burn', ailmentChance=0),
    'magnitude': Move('magnitude', 'ground', 'physical', 30, accuracy=100),
    'dynamic-punch': Move('dynamic-punch', 'fighting', 'physical', 5, power=100, accuracy=50, ailment='confusion', ailmentChance=0, minTurns=2, maxTurns=5),
    'megahorn': Move('megahorn', 'bug', 'physical', 10, power=120, accuracy=85),
    'dragon-breath': Move('dragon-breath', 'dragon', 'special', 20, power=60, accuracy=100, ailment='paralysis', ailmentChance=0),
    'baton-pass': Move('baton-pass', 'normal', 'status', 40),
    'encore': Move('encore', 'normal', 'status', 5, accuracy=100),
    'pursuit': Move('pursuit', 'dark', 'physical', 20, power=40, accuracy=100),
    'rapid-spin': Move('rapid-spin', 'normal', 'physical', 40, power=50, accuracy=100, stats=['speed'], statsStage=[1], statsChance=100),
    'sweet-scent': Move('sweet-scent', 'normal', 'status', 20, accuracy=100, stats=['eva'], statsStage=[-2]),
    'iron-tail': Move('iron-tail', 'steel', 'physical', 15, power=100, accuracy=75, stats=['def'], statsStage=[-1], statsChance=30),
    'metal-claw': Move('metal-claw', 'steel', 'physical', 35, power=50, accuracy=95, stats=['atk'], statsStage=[1], statsChance=10),
    'vital-throw': Move('vital-throw', 'fighting', 'physical', 10, power=70, priority=-1),
    'morning-sun': Move('morning-sun', 'normal', 'status', 5, healing=50),
    'synthesis': Move('synthesis', 'grass', 'status', 5, healing=50),
    'moonlight': Move('moonlight', 'fairy', 'status', 5, healing=50),
    'hidden-power': Move('hidden-power', 'normal', 'special', 15, power=60, accuracy=100),
    'cross-chop': Move('cross-chop', 'fighting', 'physical', 5, power=100, accuracy=80, critRate=1),
    'twister': Move('twister', 'dragon', 'special', 20, power=40, accuracy=100, flinchChance=20),
    'rain-dance': Move('rain-dance', 'water', 'status', 5),
    'sunny-day': Move('sunny-day', 'fire', 'status', 5),
    'crunch': Move('crunch', 'dark', 'physical', 15, power=80, accuracy=100, stats=['def'], statsStage=[-1], statsChance=20),
    'mirror-coat': Move('mirror-coat', 'psychic', 'special', 20, accuracy=100, priority=-5),
    'psych-up': Move('psych-up', 'normal', 'status', 10),
    'extreme-speed': Move('extreme-speed', 'normal', 'physical', 5, power=80, accuracy=100, priority=2),
    'ancient-power': Move('ancient-power', 'rock', 'special', 5, power=60, accuracy=100, stats=['atk', 'def', 'spAtk', 'spDef', 'speed'], statsStage=[1, 1, 1, 1, 1], statsChance=10),
    'shadow-ball': Move('shadow-ball', 'ghost', 'special', 15, power=80, accuracy=100, stats=['spDef'], statsStage=[-1], statsChance=20),
    'future-sight': Move('future-sight', 'psychic', 'special', 10, power=120, accuracy=100),
    'rock-smash': Move('rock-smash', 'fighting', 'physical', 15, power=40, accuracy=100, stats=['def'], statsStage=[-1], statsChance=50),
    'whirlpool': Move('whirlpool', 'water', 'special', 15, power=35, accuracy=85, ailment='trap', ailmentChance=0, minTurns=5, maxTurns=6),
    'beat-up': Move('beat-up', 'dark', 'physical', 10, accuracy=100, minHits=6, maxHits=6),
    'fake-out': Move('fake-out', 'normal', 'physical', 10, power=40, accuracy=100, priority=3, flinchChance=100),
    'uproar': Move('uproar', 'normal', 'special', 10, power=90, accuracy=100, minTurns=3, maxTurns=3),
    'stockpile': Move('stockpile', 'normal', 'status', 20),
    'spit-up': Move('spit-up', 'normal', 'special', 10, accuracy=100),
    'swallow': Move('swallow', 'normal', 'status', 10, healing=25),
    'heat-wave': Move('heat-wave', 'fire', 'special', 10, power=95, accuracy=90, ailment='burn', ailmentChance=0),
    'hail': Move('hail', 'ice', 'status', 10),
    'torment': Move('torment', 'dark', 'status', 15, accuracy=100, ailment='torment'),
    'flatter': Move('flatter', 'dark', 'status', 15, accuracy=100, stats=['spAtk'], statsStage=[1], ailment='confusion', minTurns=2, maxTurns=5),
    'will-o-wisp': Move('will-o-wisp', 'fire', 'status', 15, accuracy=85, ailment='burn'),
    'memento': Move('memento', 'dark', 'status', 10, accuracy=100),
    'facade': Move('facade', 'normal', 'physical', 20, power=70, accuracy=100),
    'focus-punch': Move('focus-punch', 'fighting', 'physical', 20, power=150, accuracy=100, priority=-3),
    'smelling-salts': Move('smelling-salts', 'normal', 'physical', 10, power=70, accuracy=100),
    'follow-me': Move('follow-me', 'normal', 'status', 20, priority=2),
    'nature-power': Move('nature-power', 'normal', 'status', 20),
    'charge': Move('charge', 'electric', 'status', 20, stats=['spDef'], statsStage=[1]),
    'taunt': Move('taunt', 'dark', 'status', 20, accuracy=100),
    'helping-hand': Move('helping-hand', 'normal', 'status', 20, priority=5),
    'trick': Move('trick', 'psychic', 'status', 10, accuracy=100),
    'role-play': Move('role-play', 'psychic', 'status', 10),
    'wish': Move('wish', 'normal', 'status', 10),
    'assist': Move('assist', 'normal', 'status', 20),
    'ingrain': Move('ingrain', 'grass', 'status', 20, ailment='ingrain'),
    'superpower': Move('superpower', 'fighting', 'physical', 5, power=120, accuracy=100, stats=['atk', 'def'], statsStage=[-1, -1], statsChance=100),
    'magic-coat': Move('magic-coat', 'psychic', 'status', 15, priority=4),
    'recycle': Move('recycle', 'normal', 'status', 10),
    'revenge': Move('revenge', 'fighting', 'physical', 10, power=60, accuracy=100, priority=-4),
    'brick-break': Move('brick-break', 'fighting', 'physical', 15, power=75, accuracy=100),
    'yawn': Move('yawn', 'normal', 'status', 10, ailment='yawn', minTurns=2, maxTurns=2),
    'knock-off': Move('knock-off', 'dark', 'physical', 20, power=65, accuracy=100),
    'endeavor': Move('endeavor', 'normal', 'physical', 5, accuracy=100),
    'eruption': Move('eruption', 'fire', 'special', 5, power=150, accuracy=100),
    'skill-swap': Move('skill-swap', 'psychic', 'status', 10),
    'imprison': Move('imprison', 'psychic', 'status', 10),
    'refresh': Move('refresh', 'normal', 'status', 20),
    'grudge': Move('grudge', 'ghost', 'status', 5),
    'snatch': Move('snatch', 'dark', 'status', 10, priority=4),
    'secret-power': Move('secret-power', 'normal', 'physical', 20, power=70, accuracy=100, ailmentChance=0),
    'dive': Move('dive', 'water', 'physical', 10, power=80, accuracy=100),
    'arm-thrust': Move('arm-thrust', 'fighting', 'physical', 20, power=15, accuracy=100, minHits=2, maxHits=5),
    'camouflage': Move('camouflage', 'normal', 'status', 20),
    'tail-glow': Move('tail-glow', 'bug', 'status', 20, stats=['spAtk'], statsStage=[3]),
    'luster-purge': Move('luster-purge', 'psychic', 'special', 5, power=70, accuracy=100, stats=['spDef'], statsStage=[-1], statsChance=50),
    'mist-ball': Move('mist-ball', 'psychic', 'special', 5, power=70, accuracy=100, stats=['spAtk'], statsStage=[-1], statsChance=50),
    'feather-dance': Move('feather-dance', 'flying', 'status', 15, accuracy=100, stats=['atk'], statsStage=[-2]),
    'teeter-dance': Move('teeter-dance', 'normal', 'status', 20, accuracy=100, ailment='confusion', minTurns=2, maxTurns=5),
    'blaze-kick': Move('blaze-kick', 'fire', 'physical', 10, power=85, accuracy=90, critRate=1, ailment='burn', ailmentChance=0),
    'mud-sport': Move('mud-sport', 'ground', 'status', 15),
    'ice-ball': Move('ice-ball', 'ice', 'physical', 20, power=30, accuracy=90),
    'needle-arm': Move('needle-arm', 'grass', 'physical', 15, power=60, accuracy=100, flinchChance=30),
    'slack-off': Move('slack-off', 'normal', 'status', 10, healing=50),
    'hyper-voice': Move('hyper-voice', 'normal', 'special', 10, power=90, accuracy=100),
    'poison-fang': Move('poison-fang', 'poison', 'physical', 15, power=50, accuracy=100, ailment='poison', ailmentChance=0, minTurns=15, maxTurns=15),
    'crush-claw': Move('crush-claw', 'normal', 'physical', 10, power=75, accuracy=95, stats=['def'], statsStage=[-1], statsChance=50),
    'blast-burn': Move('blast-burn', 'fire', 'special', 5, power=150, accuracy=90),
    'hydro-cannon': Move('hydro-cannon', 'water', 'special', 5, power=150, accuracy=90),
    'meteor-mash': Move('meteor-mash', 'steel', 'physical', 10, power=90, accuracy=90, stats=['atk'], statsStage=[1], statsChance=20),
    'astonish': Move('astonish', 'ghost', 'physical', 15, power=30, accuracy=100, flinchChance=30),
    'weather-ball': Move('weather-ball', 'normal', 'special', 10, power=50, accuracy=100),
    'aromatherapy': Move('aromatherapy', 'grass', 'status', 5),
    'fake-tears': Move('fake-tears', 'dark', 'status', 20, accuracy=100, stats=['spDef'], statsStage=[-2]),
    'air-cutter': Move('air-cutter', 'flying', 'special', 25, power=60, accuracy=95, critRate=1),
    'overheat': Move('overheat', 'fire', 'special', 5, power=130, accuracy=90, stats=['spAtk'], statsStage=[-2], statsChance=100),
    'odor-sleuth': Move('odor-sleuth', 'normal', 'status', 40, ailment='no-type-immunity'),
    'rock-tomb': Move('rock-tomb', 'rock', 'physical', 15, power=60, accuracy=95, stats=['speed'], statsStage=[-1], statsChance=100),
    'silver-wind': Move('silver-wind', 'bug', 'special', 5, power=60, accuracy=100, stats=['atk', 'def', 'spAtk', 'spDef', 'speed'], statsStage=[1, 1, 1, 1, 1], statsChance=10),
    'metal-sound': Move('metal-sound', 'steel', 'status', 40, accuracy=85, stats=['spDef'], statsStage=[-2]),
    'grass-whistle': Move('grass-whistle', 'grass', 'status', 15, accuracy=55, ailment='sleep', minTurns=2, maxTurns=4),
    'tickle': Move('tickle', 'normal', 'status', 20, accuracy=100, stats=['atk', 'def'], statsStage=[-1, -1]),
    'cosmic-power': Move('cosmic-power', 'psychic', 'status', 20, stats=['def', 'spDef'], statsStage=[1, 1]),
    'water-spout': Move('water-spout', 'water', 'special', 5, power=150, accuracy=100),
    'signal-beam': Move('signal-beam', 'bug', 'special', 15, power=75, accuracy=100, ailment='confusion', ailmentChance=0, minTurns=2, maxTurns=5),
    'shadow-punch': Move('shadow-punch', 'ghost', 'physical', 20, power=60),
    'extrasensory': Move('extrasensory', 'psychic', 'special', 20, power=80, accuracy=100, flinchChance=10),
    'sky-uppercut': Move('sky-uppercut', 'fighting', 'physical', 15, power=85, accuracy=90),
    'sand-tomb': Move('sand-tomb', 'ground', 'physical', 15, power=35, accuracy=85, ailment='trap', ailmentChance=0, minTurns=5, maxTurns=6),
    'sheer-cold': Move('sheer-cold', 'ice', 'special', 5, accuracy=30),
    'muddy-water': Move('muddy-water', 'water', 'special', 10, power=90, accuracy=85, stats=['acc'], statsStage=[-1], statsChance=30),
    'bullet-seed': Move('bullet-seed', 'grass', 'physical', 30, power=25, accuracy=100, minHits=2, maxHits=5),
    'aerial-ace': Move('aerial-ace', 'flying', 'physical', 20, power=60),
    'icicle-spear': Move('icicle-spear', 'ice', 'physical', 30, power=25, accuracy=100, minHits=2, maxHits=5),
    'iron-defense': Move('iron-defense', 'steel', 'status', 15, stats=['def'], statsStage=[2]),
    'block': Move('block', 'normal', 'status', 5),
    'howl': Move('howl', 'normal', 'status', 40, stats=['atk'], statsStage=[1]),
    'dragon-claw': Move('dragon-claw', 'dragon', 'physical', 15, power=80, accuracy=100),
    'frenzy-plant': Move('frenzy-plant', 'grass', 'special', 5, power=150, accuracy=90),
    'bulk-up': Move('bulk-up', 'fighting', 'status', 20, stats=['atk', 'def'], statsStage=[1, 1]),
    'bounce': Move('bounce', 'flying', 'physical', 5, power=85, accuracy=85, ailment='paralysis', ailmentChance=0),
    'mud-shot': Move('mud-shot', 'ground', 'special', 15, power=55, accuracy=95, stats=['speed'], statsStage=[-1], statsChance=100),
    'poison-tail': Move('poison-tail', 'poison', 'physical', 25, power=50, accuracy=100, critRate=1, ailment='poison', ailmentChance=0),
    'covet': Move('covet', 'normal', 'physical', 25, power=60, accuracy=100),
    'volt-tackle': Move('volt-tackle', 'electric', 'physical', 15, power=120, accuracy=100, ailment='paralysis', ailmentChance=0, dragin=-33),
    'magical-leaf': Move('magical-leaf', 'grass', 'special', 20, power=60),
    'water-sport': Move('water-sport', 'water', 'status', 15),
    'calm-mind': Move('calm-mind', 'psychic', 'status', 20, stats=['spAtk', 'spDef'], statsStage=[1, 1]),
    'leaf-blade': Move('leaf-blade', 'grass', 'physical', 15, power=90, accuracy=100, critRate=1),
    'dragon-dance': Move('dragon-dance', 'dragon', 'status', 20, stats=['atk', 'speed'], statsStage=[1, 1]),
    'rock-blast': Move('rock-blast', 'rock', 'physical', 10, power=25, accuracy=90, minHits=2, maxHits=5),
    'shock-wave': Move('shock-wave', 'electric', 'special', 20, power=60),
    'water-pulse': Move('water-pulse', 'water', 'special', 20, power=60, accuracy=100, ailment='confusion', ailmentChance=0, minTurns=2, maxTurns=5),
    'doom-desire': Move('doom-desire', 'steel', 'special', 5, power=140, accuracy=100),
    'psycho-boost': Move('psycho-boost', 'psychic', 'special', 5, power=140, accuracy=90, stats=['spAtk'], statsStage=[-2], statsChance=100),
    'roost': Move('roost', 'flying', 'status', 10, healing=50),
    'gravity': Move('gravity', 'psychic', 'status', 5),
    'miracle-eye': Move('miracle-eye', 'psychic', 'status', 40, ailment='no-type-immunity'),
    'wake-up-slap': Move('wake-up-slap', 'fighting', 'physical', 10, power=70, accuracy=100),
    'hammer-arm': Move('hammer-arm', 'fighting', 'physical', 10, power=100, accuracy=90, stats=['speed'], statsStage=[-1], statsChance=100),
    'gyro-ball': Move('gyro-ball', 'steel', 'physical', 5, accuracy=100),
    'healing-wish': Move('healing-wish', 'psychic', 'status', 10),
    'brine': Move('brine', 'water', 'special', 10, power=65, accuracy=100),
    'natural-gift': Move('natural-gift', 'normal', 'physical', 15, accuracy=100),
    'feint': Move('feint', 'normal', 'physical', 10, power=30, accuracy=100, priority=2),
    'pluck': Move('pluck', 'flying', 'physical', 20, power=60, accuracy=100),
    'tailwind': Move('tailwind', 'flying', 'status', 15),
    'acupressure': Move('acupressure', 'normal', 'status', 30),
    'metal-burst': Move('metal-burst', 'steel', 'physical', 10, accuracy=100),
    'u-turn': Move('u-turn', 'bug', 'physical', 20, power=70, accuracy=100),
    'close-combat': Move('close-combat', 'fighting', 'physical', 5, power=120, accuracy=100, stats=['def', 'spDef'], statsStage=[-1, -1], statsChance=100),
    'payback': Move('payback', 'dark', 'physical', 10, power=50, accuracy=100),
    'assurance': Move('assurance', 'dark', 'physical', 10, power=60, accuracy=100),
    'embargo': Move('embargo', 'dark', 'status', 15, accuracy=100, ailment='embargo', minTurns=5, maxTurns=5),
    'fling': Move('fling', 'dark', 'physical', 10, accuracy=100),
    'psycho-shift': Move('psycho-shift', 'psychic', 'status', 10, accuracy=100),
    'trump-card': Move('trump-card', 'normal', 'special', 5),
    'heal-block': Move('heal-block', 'psychic', 'status', 15, accuracy=100, ailment='heal-block', minTurns=5, maxTurns=5),
    'wring-out': Move('wring-out', 'normal', 'special', 5, accuracy=100),
    'power-trick': Move('power-trick', 'psychic', 'status', 10),
    'gastro-acid': Move('gastro-acid', 'poison', 'status', 10, accuracy=100),
    'lucky-chant': Move('lucky-chant', 'normal', 'status', 30),
    'me-first': Move('me-first', 'normal', 'status', 20),
    'copycat': Move('copycat', 'normal', 'status', 20),
    'power-swap': Move('power-swap', 'psychic', 'status', 10),
    'guard-swap': Move('guard-swap', 'psychic', 'status', 10),
    'punishment': Move('punishment', 'dark', 'physical', 5, accuracy=100),
    'last-resort': Move('last-resort', 'normal', 'physical', 5, power=140, accuracy=100),
    'worry-seed': Move('worry-seed', 'grass', 'status', 10, accuracy=100),
    'sucker-punch': Move('sucker-punch', 'dark', 'physical', 5, power=70, accuracy=100, priority=1),
    'toxic-spikes': Move('toxic-spikes', 'poison', 'status', 20),
    'heart-swap': Move('heart-swap', 'psychic', 'status', 10),
    'aqua-ring': Move('aqua-ring', 'water', 'status', 20),
    'magnet-rise': Move('magnet-rise', 'electric', 'status', 10),
    'flare-blitz': Move('flare-blitz', 'fire', 'physical', 15, power=120, accuracy=100, ailment='burn', ailmentChance=0, dragin=-33),
    'force-palm': Move('force-palm', 'fighting', 'physical', 10, power=60, accuracy=100, ailment='paralysis', ailmentChance=0),
    'aura-sphere': Move('aura-sphere', 'fighting', 'special', 20, power=80),
    'rock-polish': Move('rock-polish', 'rock', 'status', 20, stats=['speed'], statsStage=[2]),
    'poison-jab': Move('poison-jab', 'poison', 'physical', 20, power=80, accuracy=100, ailment='poison', ailmentChance=0),
    'dark-pulse': Move('dark-pulse', 'dark', 'special', 15, power=80, accuracy=100, flinchChance=20),
    'night-slash': Move('night-slash', 'dark', 'physical', 15, power=70, accuracy=100, critRate=1),
    'aqua-tail': Move('aqua-tail', 'water', 'physical', 10, power=90, accuracy=90),
    'seed-bomb': Move('seed-bomb', 'grass', 'physical', 15, power=80, accuracy=100),
    'air-slash': Move('air-slash', 'flying', 'special', 15, power=75, accuracy=95, flinchChance=30),
    'x-scissor': Move('x-scissor', 'bug', 'physical', 15, power=80, accuracy=100),
    'bug-buzz': Move('bug-buzz', 'bug', 'special', 10, power=90, accuracy=100, stats=['spDef'], statsStage=[-1], statsChance=10),
    'dragon-pulse': Move('dragon-pulse', 'dragon', 'special', 10, power=85, accuracy=100),
    'dragon-rush': Move('dragon-rush', 'dragon', 'physical', 10, power=100, accuracy=75, flinchChance=20),
    'power-gem': Move('power-gem', 'rock', 'special', 20, power=80, accuracy=100),
    'drain-punch': Move('drain-punch', 'fighting', 'physical', 10, power=75, accuracy=100, dragin=50),
    'vacuum-wave': Move('vacuum-wave', 'fighting', 'special', 30, power=40, accuracy=100, priority=1),
    'focus-blast': Move('focus-blast', 'fighting', 'special', 5, power=120, accuracy=70, stats=['spDef'], statsStage=[-1], statsChance=10),
    'energy-ball': Move('energy-ball', 'grass', 'special', 10, power=90, accuracy=100, stats=['spDef'], statsStage=[-1], statsChance=10),
    'brave-bird': Move('brave-bird', 'flying', 'physical', 15, power=120, accuracy=100, dragin=-33),
    'earth-power': Move('earth-power', 'ground', 'special', 10, power=90, accuracy=100, stats=['spDef'], statsStage=[-1], statsChance=10),
    'switcheroo': Move('switcheroo', 'dark', 'status', 10, accuracy=100),
    'giga-impact': Move('giga-impact', 'normal', 'physical', 5, power=150, accuracy=90),
    'nasty-plot': Move('nasty-plot', 'dark', 'status', 20, stats=['spAtk'], statsStage=[2]),
    'bullet-punch': Move('bullet-punch', 'steel', 'physical', 30, power=40, accuracy=100, priority=1),
    'avalanche': Move('avalanche', 'ice', 'physical', 10, power=60, accuracy=100, priority=-4),
    'ice-shard': Move('ice-shard', 'ice', 'physical', 30, power=40, accuracy=100, priority=1),
    'shadow-claw': Move('shadow-claw', 'ghost', 'physical', 15, power=70, accuracy=100, critRate=1),
    'thunder-fang': Move('thunder-fang', 'electric', 'physical', 15, power=65, accuracy=95, ailment='paralysis', ailmentChance=0, flinchChance=10),
    'ice-fang': Move('ice-fang', 'ice', 'physical', 15, power=65, accuracy=95, ailment='freeze', ailmentChance=0, flinchChance=10),
    'fire-fang': Move('fire-fang', 'fire', 'physical', 15, power=65, accuracy=95, ailment='burn', ailmentChance=0, flinchChance=10),
    'shadow-sneak': Move('shadow-sneak', 'ghost', 'physical', 30, power=40, accuracy=100, priority=1),
    'mud-bomb': Move('mud-bomb', 'ground', 'special', 10, power=65, accuracy=85, stats=['acc'], statsStage=[-1], statsChance=30),
    'psycho-cut': Move('psycho-cut', 'psychic', 'physical', 20, power=70, accuracy=100, critRate=1),
    'zen-headbutt': Move('zen-headbutt', 'psychic', 'physical', 15, power=80, accuracy=90, flinchChance=20),
    'mirror-shot': Move('mirror-shot', 'steel', 'special', 10, power=65, accuracy=85, stats=['acc'], statsStage=[-1], statsChance=30),
    'flash-cannon': Move('flash-cannon', 'steel', 'special', 10, power=80, accuracy=100, stats=['spDef'], statsStage=[-1], statsChance=10),
    'rock-climb': Move('rock-climb', 'normal', 'physical', 20, power=90, accuracy=85, ailment='confusion', ailmentChance=0, minTurns=2, maxTurns=5),
    'defog': Move('defog', 'flying', 'status', 15),
    'trick-room': Move('trick-room', 'psychic', 'status', 5, priority=-7),
    'draco-meteor': Move('draco-meteor', 'dragon', 'special', 5, power=130, accuracy=90, stats=['spAtk'], statsStage=[-2], statsChance=100),
    'discharge': Move('discharge', 'electric', 'special', 15, power=80, accuracy=100, ailment='paralysis', ailmentChance=0),
    'lava-plume': Move('lava-plume', 'fire', 'special', 15, power=80, accuracy=100, ailment='burn', ailmentChance=0),
    'leaf-storm': Move('leaf-storm', 'grass', 'special', 5, power=130, accuracy=90, stats=['spAtk'], statsStage=[-2], statsChance=100),
    'power-whip': Move('power-whip', 'grass', 'physical', 10, power=120, accuracy=85),
    'rock-wrecker': Move('rock-wrecker', 'rock', 'physical', 5, power=150, accuracy=90),
    'cross-poison': Move('cross-poison', 'poison', 'physical', 20, power=70, accuracy=100, critRate=1, ailment='poison', ailmentChance=0),
    'gunk-shot': Move('gunk-shot', 'poison', 'physical', 5, power=120, accuracy=80, ailment='poison', ailmentChance=0),
    'iron-head': Move('iron-head', 'steel', 'physical', 15, power=80, accuracy=100, flinchChance=30),
    'magnet-bomb': Move('magnet-bomb', 'steel', 'physical', 20, power=60),
    'stone-edge': Move('stone-edge', 'rock', 'physical', 5, power=100, accuracy=80, critRate=1),
    'captivate': Move('captivate', 'normal', 'status', 20, accuracy=100, stats=['spAtk'], statsStage=[-2]),
    'stealth-rock': Move('stealth-rock', 'rock', 'status', 20),
    'grass-knot': Move('grass-knot', 'grass', 'special', 20, accuracy=100),
    'chatter': Move('chatter', 'flying', 'special', 20, power=65, accuracy=100, ailment='confusion', ailmentChance=0, minTurns=2, maxTurns=5),
    'judgment': Move('judgment', 'normal', 'special', 10, power=100, accuracy=100),
    'bug-bite': Move('bug-bite', 'bug', 'physical', 20, power=60, accuracy=100),
    'charge-beam': Move('charge-beam', 'electric', 'special', 10, power=50, accuracy=90, stats=['spAtk'], statsStage=[1], statsChance=70),
    'wood-hammer': Move('wood-hammer', 'grass', 'physical', 15, power=120, accuracy=100, dragin=-33),
    'aqua-jet': Move('aqua-jet', 'water', 'physical', 20, power=40, accuracy=100, priority=1),
    'attack-order': Move('attack-order', 'bug', 'physical', 15, power=90, accuracy=100, critRate=1),
    'defend-order': Move('defend-order', 'bug', 'status', 10, stats=['def', 'spDef'], statsStage=[1, 1]),
    'heal-order': Move('heal-order', 'bug', 'status', 10, healing=50),
    'head-smash': Move('head-smash', 'rock', 'physical', 5, power=150, accuracy=80, dragin=-50),
    'double-hit': Move('double-hit', 'normal', 'physical', 10, power=35, accuracy=90, minHits=2, maxHits=2),
    'roar-of-time': Move('roar-of-time', 'dragon', 'special', 5, power=150, accuracy=90),
    'spacial-rend': Move('spacial-rend', 'dragon', 'special', 5, power=100, accuracy=95, critRate=1),
    'lunar-dance': Move('lunar-dance', 'psychic', 'status', 10),
    'crush-grip': Move('crush-grip', 'normal', 'physical', 5, accuracy=100),
    'magma-storm': Move('magma-storm', 'fire', 'special', 5, power=100, accuracy=75, ailment='trap', ailmentChance=0, minTurns=5, maxTurns=6),
    'dark-void': Move('dark-void', 'dark', 'status', 10, accuracy=50, ailment='sleep', minTurns=2, maxTurns=4),
    'seed-flare': Move('seed-flare', 'grass', 'special', 5, power=120, accuracy=85, stats=['spDef'], statsStage=[-2], statsChance=40),
    'ominous-wind': Move('ominous-wind', 'ghost', 'special', 5, power=60, accuracy=100, stats=['atk', 'def', 'spAtk', 'spDef', 'speed'], statsStage=[1, 1, 1, 1, 1], statsChance=10, ailmentChance=10),
    'shadow-force': Move('shadow-force', 'ghost', 'physical', 5, power=120, accuracy=100),
    'hone-claws': Move('hone-claws', 'dark', 'status', 15, stats=['atk', 'acc'], statsStage=[1, 1]),
    'wide-guard': Move('wide-guard', 'rock', 'status', 10, priority=3),
    'guard-split': Move('guard-split', 'psychic', 'status', 10),
    'power-split': Move('power-split', 'psychic', 'status', 10),
    'wonder-room': Move('wonder-room', 'psychic', 'status', 10),
    'psyshock': Move('psyshock', 'psychic', 'special', 10, power=80, accuracy=100),
    'venoshock': Move('venoshock', 'poison', 'special', 10, power=65, accuracy=100),
    'autotomize': Move('autotomize', 'steel', 'status', 15, stats=['speed'], statsStage=[2]),
    'rage-powder': Move('rage-powder', 'bug', 'status', 20, priority=2),
    'telekinesis': Move('telekinesis', 'psychic', 'status', 15, ailment='unknown', minTurns=3, maxTurns=3),
    'magic-room': Move('magic-room', 'psychic', 'status', 10),
    'smack-down': Move('smack-down', 'rock', 'physical', 15, power=50, accuracy=100, ailment='unknown', ailmentChance=0),
    'storm-throw': Move('storm-throw', 'fighting', 'physical', 10, power=60, accuracy=100, critRate=6),
    'flame-burst': Move('flame-burst', 'fire', 'special', 15, power=70, accuracy=100),
    'sludge-wave': Move('sludge-wave', 'poison', 'special', 10, power=95, accuracy=100, ailment='poison', ailmentChance=0),
    'quiver-dance': Move('quiver-dance', 'bug', 'status', 20, stats=['spAtk', 'spDef', 'speed'], statsStage=[1, 1, 1]),
    'heavy-slam': Move('heavy-slam', 'steel', 'physical', 10, accuracy=100),
    'synchronoise': Move('synchronoise', 'psychic', 'special', 10, power=120, accuracy=100),
    'electro-ball': Move('electro-ball', 'electric', 'special', 10, accuracy=100),
    'soak': Move('soak', 'water', 'status', 20, accuracy=100),
    'flame-charge': Move('flame-charge', 'fire', 'physical', 20, power=50, accuracy=100, stats=['speed'], statsStage=[1], statsChance=100),
    'coil': Move('coil', 'poison', 'status', 20, stats=['atk', 'def', 'acc'], statsStage=[1, 1, 1]),
    'low-sweep': Move('low-sweep', 'fighting', 'physical', 20, power=65, accuracy=100, stats=['speed'], statsStage=[-1], statsChance=100),
    'acid-spray': Move('acid-spray', 'poison', 'special', 20, power=40, accuracy=100, stats=['spDef'], statsStage=[-2], statsChance=100),
    'foul-play': Move('foul-play', 'dark', 'physical', 15, power=95, accuracy=100),
    'simple-beam': Move('simple-beam', 'normal', 'status', 15, accuracy=100),
    'entrainment': Move('entrainment', 'normal', 'status', 15, accuracy=100),
    'after-you': Move('after-you', 'normal', 'status', 15),
    'round': Move('round', 'normal', 'special', 15, power=60, accuracy=100),
    'echoed-voice': Move('echoed-voice', 'normal', 'special', 15, power=40, accuracy=100),
    'chip-away': Move('chip-away', 'normal', 'physical', 20, power=70, accuracy=100),
    'clear-smog': Move('clear-smog', 'poison', 'special', 15, power=50),
    'stored-power': Move('stored-power', 'psychic', 'special', 10, power=20, accuracy=100),
    'quick-guard': Move('quick-guard', 'fighting', 'status', 15, priority=3),
    'ally-switch': Move('ally-switch', 'psychic', 'status', 15, priority=2),
    'scald': Move('scald', 'water', 'special', 15, power=80, accuracy=100, ailment='burn', ailmentChance=0),
    'shell-smash': Move('shell-smash', 'normal', 'status', 15),
    'heal-pulse': Move('heal-pulse', 'psychic', 'status', 10, healing=50),
    'hex': Move('hex', 'ghost', 'special', 10, power=65, accuracy=100),
    'sky-drop': Move('sky-drop', 'flying', 'physical', 10, power=60, accuracy=100),
    'shift-gear': Move('shift-gear', 'steel', 'status', 10, stats=['atk', 'speed'], statsStage=[1, 2]),
    'circle-throw': Move('circle-throw', 'fighting', 'physical', 10, power=60, accuracy=90, priority=-6),
    'incinerate': Move('incinerate', 'fire', 'special', 15, power=60, accuracy=100),
    'quash': Move('quash', 'dark', 'status', 15, accuracy=100),
    'acrobatics': Move('acrobatics', 'flying', 'physical', 15, power=55, accuracy=100),
    'reflect-type': Move('reflect-type', 'normal', 'status', 15),
    'retaliate': Move('retaliate', 'normal', 'physical', 5, power=70, accuracy=100),
    'final-gambit': Move('final-gambit', 'fighting', 'special', 5, accuracy=100),
    'bestow': Move('bestow', 'normal', 'status', 15),
    'inferno': Move('inferno', 'fire', 'special', 5, power=100, accuracy=50, ailment='burn', ailmentChance=0),
    'water-pledge': Move('water-pledge', 'water', 'special', 10, power=80, accuracy=100),
    'fire-pledge': Move('fire-pledge', 'fire', 'special', 10, power=80, accuracy=100),
    'grass-pledge': Move('grass-pledge', 'grass', 'special', 10, power=80, accuracy=100),
    'volt-switch': Move('volt-switch', 'electric', 'special', 20, power=70, accuracy=100),
    'struggle-bug': Move('struggle-bug', 'bug', 'special', 20, power=50, accuracy=100, stats=['spAtk'], statsStage=[-1], statsChance=100),
    'bulldoze': Move('bulldoze', 'ground', 'physical', 20, power=60, accuracy=100, stats=['speed'], statsStage=[-1], statsChance=100),
    'frost-breath': Move('frost-breath', 'ice', 'special', 10, power=60, accuracy=90, critRate=6, ailmentChance=0),
    'dragon-tail': Move('dragon-tail', 'dragon', 'physical', 10, power=60, accuracy=90, priority=-6),
    'work-up': Move('work-up', 'normal', 'status', 30, stats=['atk', 'spAtk'], statsStage=[1, 1]),
    'electroweb': Move('electroweb', 'electric', 'special', 15, power=55, accuracy=95, stats=['speed'], statsStage=[-1], statsChance=100),
    'wild-charge': Move('wild-charge', 'electric', 'physical', 15, power=90, accuracy=100, dragin=-25),
    'drill-run': Move('drill-run', 'ground', 'physical', 10, power=80, accuracy=95, critRate=1),
    'dual-chop': Move('dual-chop', 'dragon', 'physical', 15, power=40, accuracy=90, minHits=2, maxHits=2),
    'heart-stamp': Move('heart-stamp', 'psychic', 'physical', 25, power=60, accuracy=100, flinchChance=30),
    'horn-leech': Move('horn-leech', 'grass', 'physical', 10, power=75, accuracy=100, dragin=50),
    'sacred-sword': Move('sacred-sword', 'fighting', 'physical', 15, power=90, accuracy=100),
    'razor-shell': Move('razor-shell', 'water', 'physical', 10, power=75, accuracy=95, stats=['def'], statsStage=[-1], statsChance=50),
    'heat-crash': Move('heat-crash', 'fire', 'physical', 10, accuracy=100),
    'leaf-tornado': Move('leaf-tornado', 'grass', 'special', 10, power=65, accuracy=90, stats=['acc'], statsStage=[-1], statsChance=50),
    'steamroller': Move('steamroller', 'bug', 'physical', 20, power=65, accuracy=100, flinchChance=30),
    'cotton-guard': Move('cotton-guard', 'grass', 'status', 10, stats=['def'], statsStage=[3]),
    'night-daze': Move('night-daze', 'dark', 'special', 10, power=85, accuracy=95, stats=['acc'], statsStage=[-1], statsChance=40),
    'psystrike': Move('psystrike', 'psychic', 'special', 10, power=100, accuracy=100),
    'tail-slap': Move('tail-slap', 'normal', 'physical', 10, power=25, accuracy=85, minHits=2, maxHits=5),
    'hurricane': Move('hurricane', 'flying', 'special', 10, power=110, accuracy=70, ailment='confusion', ailmentChance=0, minTurns=2, maxTurns=5),
    'head-charge': Move('head-charge', 'normal', 'physical', 15, power=120, accuracy=100, dragin=-25),
    'gear-grind': Move('gear-grind', 'steel', 'physical', 15, power=50, accuracy=85, minHits=2, maxHits=2),
    'searing-shot': Move('searing-shot', 'fire', 'special', 5, power=100, accuracy=100, ailment='burn', ailmentChance=0),
    'techno-blast': Move('techno-blast', 'normal', 'special', 5, power=120, accuracy=100),
    'relic-song': Move('relic-song', 'normal', 'special', 10, power=75, accuracy=100, ailment='sleep', ailmentChance=0, minTurns=2, maxTurns=4),
    'secret-sword': Move('secret-sword', 'fighting', 'special', 10, power=85, accuracy=100),
    'glaciate': Move('glaciate', 'ice', 'special', 10, power=65, accuracy=95, stats=['speed'], statsStage=[-1], statsChance=100),
    'bolt-strike': Move('bolt-strike', 'electric', 'physical', 5, power=130, accuracy=85, ailment='paralysis', ailmentChance=0),
    'blue-flare': Move('blue-flare', 'fire', 'special', 5, power=130, accuracy=85, ailment='burn', ailmentChance=0),
    'fiery-dance': Move('fiery-dance', 'fire', 'special', 10, power=80, accuracy=100, stats=['spAtk'], statsStage=[1], statsChance=50),
    'freeze-shock': Move('freeze-shock', 'ice', 'physical', 5, power=140, accuracy=90, ailment='paralysis', ailmentChance=0),
    'ice-burn': Move('ice-burn', 'ice', 'special', 5, power=140, accuracy=90, ailment='burn', ailmentChance=0),
    'snarl': Move('snarl', 'dark', 'special', 15, power=55, accuracy=95, stats=['spAtk'], statsStage=[-1], statsChance=100),
    'icicle-crash': Move('icicle-crash', 'ice', 'physical', 10, power=85, accuracy=90, flinchChance=30),
    'v-create': Move('v-create', 'fire', 'physical', 5, power=180, accuracy=95, stats=['def', 'spDef', 'speed'], statsStage=[-1, -1, -1], statsChance=100),
    'fusion-flare': Move('fusion-flare', 'fire', 'special', 5, power=100, accuracy=100),
    'fusion-bolt': Move('fusion-bolt', 'electric', 'physical', 5, power=100, accuracy=100),
    'flying-press': Move('flying-press', 'fighting', 'physical', 10, power=100, accuracy=95),
    'mat-block': Move('mat-block', 'fighting', 'status', 10),
    'belch': Move('belch', 'poison', 'special', 10, power=120, accuracy=90),
    'rototiller': Move('rototiller', 'ground', 'status', 10, stats=['atk', 'spAtk'], statsStage=[1, 1], statsChance=100),
    'sticky-web': Move('sticky-web', 'bug', 'status', 20),
    'fell-stinger': Move('fell-stinger', 'bug', 'physical', 25, power=50, accuracy=100),
    'phantom-force': Move('phantom-force', 'ghost', 'physical', 10, power=90, accuracy=100),
    'trick-or-treat': Move('trick-or-treat', 'ghost', 'status', 20, accuracy=100),
    'noble-roar': Move('noble-roar', 'normal', 'status', 30, accuracy=100, stats=['atk', 'spAtk'], statsStage=[-1, -1], statsChance=100),
    'ion-deluge': Move('ion-deluge', 'electric', 'status', 25, priority=1),
    'parabolic-charge': Move('parabolic-charge', 'electric', 'special', 20, power=65, accuracy=100, dragin=50),
    'forests-curse': Move('forests-curse', 'grass', 'status', 20, accuracy=100),
    'petal-blizzard': Move('petal-blizzard', 'grass', 'physical', 15, power=90, accuracy=100),
    'freeze-dry': Move('freeze-dry', 'ice', 'special', 20, power=70, accuracy=100, ailment='freeze', ailmentChance=0),
    'disarming-voice': Move('disarming-voice', 'fairy', 'special', 15, power=40),
    'parting-shot': Move('parting-shot', 'dark', 'status', 20, accuracy=100, stats=['atk', 'spAtk'], statsStage=[-1, -1], statsChance=100),
    'topsy-turvy': Move('topsy-turvy', 'dark', 'status', 20),
    'draining-kiss': Move('draining-kiss', 'fairy', 'special', 10, power=50, accuracy=100, dragin=75),
    'crafty-shield': Move('crafty-shield', 'fairy', 'status', 10, priority=3),
    'flower-shield': Move('flower-shield', 'fairy', 'status', 10, stats=['def'], statsStage=[1], statsChance=100),
    'grassy-terrain': Move('grassy-terrain', 'grass', 'status', 10),
    'misty-terrain': Move('misty-terrain', 'fairy', 'status', 10),
    'electrify': Move('electrify', 'electric', 'status', 20),
    'play-rough': Move('play-rough', 'fairy', 'physical', 10, power=90, accuracy=90, stats=['atk'], statsStage=[-1], statsChance=10),
    'fairy-wind': Move('fairy-wind', 'fairy', 'special', 30, power=40, accuracy=100),
    'moonblast': Move('moonblast', 'fairy', 'special', 15, power=95, accuracy=100, stats=['spAtk'], statsStage=[-1], statsChance=30),
    'boomburst': Move('boomburst', 'normal', 'special', 10, power=140, accuracy=100),
    'fairy-lock': Move('fairy-lock', 'fairy', 'status', 10),
    'kings-shield': Move('kings-shield', 'steel', 'status', 10, priority=4),
    'play-nice': Move('play-nice', 'normal', 'status', 20, stats=['atk'], statsStage=[-1], statsChance=100),
    'confide': Move('confide', 'normal', 'status', 20, stats=['spAtk'], statsStage=[-1], statsChance=100),
    'diamond-storm': Move('diamond-storm', 'rock', 'physical', 5, power=100, accuracy=95, stats=['def'], statsStage=[2], statsChance=50),
    'steam-eruption': Move('steam-eruption', 'water', 'special', 5, power=110, accuracy=95, ailment='burn', ailmentChance=0),
    'hyperspace-hole': Move('hyperspace-hole', 'psychic', 'special', 5, power=80),
    'water-shuriken': Move('water-shuriken', 'water', 'special', 20, power=15, accuracy=100, priority=1, minHits=2, maxHits=5),
    'mystical-fire': Move('mystical-fire', 'fire', 'special', 10, power=75, accuracy=100, stats=['spAtk'], statsStage=[-1], statsChance=100),
    'spiky-shield': Move('spiky-shield', 'grass', 'status', 10, priority=4),
    'aromatic-mist': Move('aromatic-mist', 'fairy', 'status', 20, stats=['spDef'], statsStage=[1]),
    'eerie-impulse': Move('eerie-impulse', 'electric', 'status', 15, accuracy=100, stats=['spAtk'], statsStage=[-2]),
    'venom-drench': Move('venom-drench', 'poison', 'status', 20, accuracy=100, stats=['atk', 'spAtk', 'speed'], statsStage=[-1, -1, -1], statsChance=100),
    'powder': Move('powder', 'bug', 'status', 20, accuracy=100, priority=1),
    'geomancy': Move('geomancy', 'fairy', 'status', 10, stats=['spAtk', 'spDef', 'speed'], statsStage=[2, 2, 2]),
    'magnetic-flux': Move('magnetic-flux', 'electric', 'status', 20, stats=['def', 'spDef'], statsStage=[1, 1]),
    'happy-hour': Move('happy-hour', 'normal', 'status', 30),
    'electric-terrain': Move('electric-terrain', 'electric', 'status', 10),
    'dazzling-gleam': Move('dazzling-gleam', 'fairy', 'special', 10, power=80, accuracy=100),
    'celebrate': Move('celebrate', 'normal', 'status', 40),
    'hold-hands': Move('hold-hands', 'normal', 'status', 40),
    'baby-doll-eyes': Move('baby-doll-eyes', 'fairy', 'status', 30, accuracy=100, priority=1, stats=['atk'], statsStage=[-1]),
}