natureList = {
    'hardy': {'atk': 1, 'def': 1, 'spAtk': 1, 'spDef': 1, 'speed': 1},
    'lonely': {'atk': 1.1, 'def': 0.9, 'spAtk': 1, 'spDef': 1, 'speed': 1},
    'brave': {'atk': 1.1, 'def': 1, 'spAtk': 1, 'spDef': 1, 'speed': 0.9},
    'adamant': {'atk': 1.1, 'def': 1, 'spAtk': 0.9, 'spDef': 1, 'speed': 1},
    'naughty': {'atk': 1.1, 'def': 1, 'spAtk': 1, 'spDef': 0.9, 'speed': 1},
    'bold': {'atk': 0.9, 'def': 1.1, 'spAtk': 1, 'spDef': 1, 'speed': 1},
    'docile': {'atk': 1, 'def': 1, 'spAtk': 1, 'spDef': 1, 'speed': 1},
    'relaxed': {'atk': 1, 'def': 1.1, 'spAtk': 1, 'spDef': 1, 'speed': 0.9},
    'impish': {'atk': 1, 'def': 1.1, 'spAtk': 0.9, 'spDef': 1, 'speed': 1},
    'lax': {'atk': 1, 'def': 1.1, 'spAtk': 1, 'spDef': 0.9, 'speed': 1},
    'timid': {'atk': 0.9, 'def': 1, 'spAtk': 1, 'spDef': 1, 'speed': 1.1},
    'hasty': {'atk': 1, 'def': 0.9, 'spAtk': 1, 'spDef': 1, 'speed': 1.1},
    'serious': {'atk': 1, 'def': 1, 'spAtk': 1, 'spDef': 1, 'speed': 1},
    'jolly': {'atk': 1, 'def': 1, 'spAtk': 0.9, 'spDef': 1, 'speed': 1.1},
    'naive': {'atk': 1, 'def': 1, 'spAtk': 1, 'spDef': 0.9, 'speed': 1.1},
    'modest': {'atk': 0.9, 'def': 1, 'spAtk': 1.1, 'spDef': 1, 'speed': 1},
    'mild': {'atk': 1, 'def': 0.9, 'spAtk': 1.1, 'spDef': 1, 'speed': 1},
    'quiet': {'atk': 1, 'def': 1, 'spAtk': 1.1, 'spDef': 1, 'speed': 0.9},
    'bashful': {'atk': 1, 'def': 1, 'spAtk': 1, 'spDef': 1, 'speed': 1},
    'rash': {'atk': 1, 'def': 1, 'spAtk': 1.1, 'spDef': 0.9, 'speed': 1},
    'calm': {'atk': 0.9, 'def': 1, 'spAtk': 1, 'spDef': 1.1, 'speed': 1},
    'gentle': {'atk': 1, 'def': 0.9, 'spAtk': 1, 'spDef': 1.1, 'speed': 1},
    'sassy': {'atk': 1, 'def': 1, 'spAtk': 1, 'spDef': 1.1, 'speed': 0.9},
    'careful': {'atk': 1, 'def': 1, 'spAtk': 0.9, 'spDef': 1.1, 'speed': 1},
    'quirky': {'atk': 1, 'def': 1, 'spAtk': 1, 'spDef': 1, 'speed': 1}
}
